#!/usr/bin/env python
from __future__ import print_function

import rospy

if __name__ == '__main__':
    face_finder = face_localizer()

        rate = rospy.Rate(1)
        while not rospy.is_shutdown():
            face_finder.find_faces()
            rate.sleep()

        cv2.destroyAllWindows()